---
- hosts: localhost
  connection: local
  tasks:
    - name: Load AWS credentials
      include_vars:
        file: secret/aws_cred.yml
    - name: Create security group
      ec2_group:
        name: mysqldb_sec_group
        description: "Group to allow access to MySQL server"
        region: eu-west-1
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_key_id }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 3306
            to_port: 3306
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            from_port: 0
            to_port: 65535
            cidr_ip: 0.0.0.0/0
      register: sec_group

    - name: Create EC2 instance
      ec2:
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_key_id }}"
        key_name: test
        region: eu-west-1
        image: ami-0d4002a13019b7703
        wait: yes
        instance_type: t2.micro
        vpc_subnet_id: "{{ subnet_id }}"
        group_id: "{{ sec_group.group_id }}"
        volumes:
        - device_name: /dev/sda1
          volume_size: 16
          delete_on_termination: true      
        count_tag:
          type: DB
        exact_count: 1
        assign_public_ip: yes
      register: ec2_instance

    - name: create file with Instance ip for Ansible
      copy:
        dest: hosts
        content:
          "{{ ec2_instance['tagged_instances'][0]['public_ip'] }}"


